# Generated by Django 3.2.7 on 2022-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('Uname', models.CharField(default='unnamed', max_length=25, verbose_name='用户名')),
                ('Passwd', models.CharField(default='password-not-set', max_length=25, verbose_name='密码')),
                ('OrgID', models.IntegerField(verbose_name='班级ID')),
                ('STUID', models.IntegerField(verbose_name='学号')),
                ('Rank', models.IntegerField(verbose_name='等级')),
                ('Header', models.ImageField(default='/static/img/header_default.png', upload_to='userHeader', verbose_name='用户头像')),
                ('EXP', models.IntegerField(verbose_name='用户经验值')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
    ]
