# Generated by Django 3.2.7 on 2022-03-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Rank',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
    ]
