# Generated by Django 3.2.7 on 2022-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommunityName', models.CharField(max_length=20, verbose_name='社区名称')),
                ('PostCount', models.IntegerField(verbose_name='帖子数')),
                ('Renewal', models.DateTimeField(verbose_name='最后更新时间')),
                ('Poster', models.ImageField(default='/static/img/header_default.png', upload_to='communityHeader', verbose_name='社区封面图像')),
                ('Description', models.CharField(max_length=256, verbose_name='社区简介')),
            ],
            options={
                'verbose_name': '社区名称',
                'verbose_name_plural': '社区名称',
                'db_table': 'Community',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=256, verbose_name='文件名')),
                ('Uri', models.CharField(max_length=256, verbose_name='文件相对地址')),
                ('Theme', models.CharField(max_length=15, verbose_name='分类名称')),
                ('Renewal', models.DateTimeField(verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '课程文件',
                'verbose_name_plural': '课程文件',
                'db_table': 'File',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('OrgID', models.AutoField(primary_key=True, serialize=False, verbose_name='组织ID')),
                ('OrgName', models.CharField(max_length=25, verbose_name='组织名称')),
                ('MonitorID', models.IntegerField(verbose_name='班长ID')),
                ('Description', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(verbose_name='创建时间')),
                ('HasImage', models.BooleanField(verbose_name='是否含有图片')),
                ('Content', models.CharField(max_length=300, verbose_name='帖子内容')),
            ],
            options={
                'verbose_name': '主题帖子',
                'verbose_name_plural': '主题帖子',
                'db_table': 'Post',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='Uname',
            field=models.CharField(default='unnamed', max_length=20, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(verbose_name='创建时间')),
                ('HasImage', models.BooleanField(verbose_name='是否含有图片')),
                ('Title', models.CharField(max_length=35, verbose_name='主题标题')),
                ('ImageUri', models.ImageField(default='/static/img/header_default.png', upload_to='TopicHeader', verbose_name='话题封面图像')),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.community', verbose_name='所属课程社区')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '社区主题',
                'verbose_name_plural': '社区主题',
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=20, verbose_name='计划名称')),
                ('Time', models.DateTimeField(verbose_name='提醒时间')),
                ('Status', models.BooleanField(verbose_name='当前状态')),
                ('Tag', models.IntegerField(verbose_name='标签颜色')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '提醒事项',
                'verbose_name_plural': '提醒事项',
                'db_table': 'ToDoList',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.IntegerField(verbose_name='绑定课程ID')),
                ('TimeStart', models.DateTimeField(verbose_name='任务开始时间')),
                ('TimeDue', models.DateTimeField(verbose_name='任务到期时间')),
                ('Status', models.BooleanField(verbose_name='当前状态')),
                ('Description', models.CharField(max_length=256, verbose_name='任务描述')),
                ('TaskName', models.CharField(max_length=30, verbose_name='任务标题')),
                ('Creator', models.CharField(max_length=20, verbose_name='创建者')),
                ('AckCount', models.IntegerField(verbose_name='已知人数')),
                ('Org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '班级任务',
                'verbose_name_plural': '班级任务',
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DurationStart', models.IntegerField(verbose_name='课程开始相对时间')),
                ('DurationEnd', models.IntegerField(verbose_name='课程结束相对时间')),
                ('Repeat', models.IntegerField(verbose_name='课程日期')),
                ('CurName', models.CharField(max_length=20, verbose_name='课程名称')),
                ('Tag', models.IntegerField(verbose_name='标签颜色')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'Shedule',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uri', models.ImageField(default='/static/img/header_default.png', upload_to='PostImage', verbose_name='帖子图像')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.post', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'PostImage',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.topic', verbose_name='所属主题'),
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user', verbose_name='发表者'),
        ),
        migrations.AddField(
            model_name='community',
            name='Administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.user', verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='OrgID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.organization', verbose_name='所属班级ID'),
        ),
    ]
