# Generated by Django 3.2.7 on 2022-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EXP',
            field=models.IntegerField(default=0, verbose_name='用户经验值'),
        ),
    ]
