# Generated by Django 3.2.7 on 2022-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_user_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='OrgID',
            field=models.IntegerField(default=-1, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='OrgID',
            field=models.IntegerField(default=-1, verbose_name='组织ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='STUID',
            field=models.IntegerField(default=-1, verbose_name='学号'),
        ),
    ]
