# Generated by Django 3.2.7 on 2022-04-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_schedule_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Repeat',
            new_name='Day',
        ),
    ]
