# Generated by Django 3.2.7 on 2022-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_rename_repeat_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='UUID',
            field=models.UUIDField(default='51a5e3e7-d30f-4b43-9c84-bf01632c6022', verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='UUID',
            field=models.UUIDField(default='51a5e3e7-d30f-4b43-9c84-bf01632c6022', verbose_name='uuid'),
        ),
    ]
