# Generated by Django 3.2.7 on 2022-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_todolist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgtask',
            name='TimeDue',
            field=models.IntegerField(verbose_name='任务到期时间'),
        ),
        migrations.AlterField(
            model_name='orgtask',
            name='TimeStart',
            field=models.IntegerField(verbose_name='任务开始时间'),
        ),
    ]
