# Generated by Django 3.2.7 on 2022-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20220408_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgtask',
            name='AckCount',
            field=models.IntegerField(default=0, verbose_name='已知人数'),
        ),
    ]
