# Generated by Django 3.2.7 on 2022-04-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_orgtask_ackcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField(verbose_name='所属任务ID')),
                ('UID', models.IntegerField(verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '任务收到统计',
                'verbose_name_plural': '任务收到统计',
                'db_table': 'TaskAck',
            },
        ),
    ]
