# Generated by Django 3.2.7 on 2022-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_taskack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Renewal',
            field=models.IntegerField(verbose_name='最后更新时间'),
        ),
    ]
