# Generated by Django 3.2.7 on 2022-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_community_postcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Renewal',
            field=models.IntegerField(default=0, verbose_name='最后更新时间'),
        ),
    ]
