# Generated by Django 3.2.7 on 2022-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_communitytopic_hasimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytopic',
            name='Time',
            field=models.IntegerField(verbose_name='创建时间'),
        ),
    ]
