# Generated by Django 3.2.7 on 2022-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_alter_topicpost_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name='所属用户ID')),
                ('FoldName', models.CharField(default='untitled fold', max_length=15, verbose_name='归类主题名')),
                ('Filename', models.CharField(default='untitled file', max_length=50, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
                'db_table': 'FileModel',
            },
        ),
    ]
