# Generated by Django 3.2.7 on 2022-04-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='OrgID',
            field=models.IntegerField(default=-1, verbose_name='所属组织ID'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='Renewal',
            field=models.IntegerField(default=0, verbose_name='最后访问时间'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='UID',
            field=models.IntegerField(default=-1, verbose_name='所属用户ID'),
        ),
    ]
