# Generated by Django 3.2.7 on 2022-04-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_rename_foldname_filemodel_foldername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='EXP',
        ),
        migrations.AddField(
            model_name='user',
            name='Accumulate',
            field=models.IntegerField(default=0, verbose_name='积累学习时长（秒）'),
        ),
    ]
