# Generated by Django 3.2.7 on 2022-04-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20220424_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Accumulate',
            new_name='Accumulation',
        ),
    ]
