# Generated by Django 3.2.7 on 2022-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_rename_accumulate_user_accumulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Accumulation',
        ),
        migrations.AddField(
            model_name='user',
            name='LastAwardTime',
            field=models.IntegerField(default=0, verbose_name='上次进入排行榜时间'),
        ),
    ]
