# Generated by Django 3.2.7 on 2022-04-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20220424_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='LastAwardTime',
        ),
        migrations.AddField(
            model_name='user',
            name='Accumulation',
            field=models.IntegerField(default=0, verbose_name='积累学习时长（秒）'),
        ),
    ]
