# Generated by Django 3.2.7 on 2022-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20220428_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EXP',
            field=models.IntegerField(default=0, verbose_name='用户经验值'),
        ),
    ]
