# Generated by Django 3.2.7 on 2022-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_user_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytopic',
            name='Stars',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='topicpost',
            name='Stars',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
