# Generated by Django 3.2.7 on 2022-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_auto_20220428_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=-1, verbose_name='点赞类型 0 主题 1 帖子')),
                ('UID', models.IntegerField(default=-1, verbose_name='点赞者ID')),
                ('TargetID', models.IntegerField(default=-1, verbose_name='点赞对象ID')),
            ],
            options={
                'verbose_name': '社区点赞',
                'verbose_name_plural': '社区点赞',
                'db_table': 'CommunityStars',
            },
        ),
    ]
