# Generated by Django 3.2.7 on 2022-04-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_rename_creator_communitytopic_uid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgtask',
            table='OrgTask',
        ),
    ]
