# Generated by Django 3.2.7 on 2022-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_alter_orgtask_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgtask',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='当前状态'),
        ),
    ]
